// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQqjvJK3_n2KzuFmQ9izd81XN3p1w6iOU',
    appId: '1:192964375295:web:f7b4b947fbab474a0492ca',
    messagingSenderId: '192964375295',
    projectId: 'budgettracker-48d4c',
    authDomain: 'budgettracker-48d4c.firebaseapp.com',
    storageBucket: 'budgettracker-48d4c.appspot.com',
    measurementId: 'G-6T2JSRX3YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4m-fFuGAo8-drzMb3VdXZo5vruq2cw9s',
    appId: '1:192964375295:android:09e37b666cae1f870492ca',
    messagingSenderId: '192964375295',
    projectId: 'budgettracker-48d4c',
    storageBucket: 'budgettracker-48d4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxcQlRW-Rh57QhGPaodCL1Mpk2bYzcToA',
    appId: '1:192964375295:ios:77c6b424c2c446bd0492ca',
    messagingSenderId: '192964375295',
    projectId: 'budgettracker-48d4c',
    storageBucket: 'budgettracker-48d4c.appspot.com',
    iosClientId: '192964375295-hvvqblh7k531s3u2c2tsvrogdu8ur3nl.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgettrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxcQlRW-Rh57QhGPaodCL1Mpk2bYzcToA',
    appId: '1:192964375295:ios:77c6b424c2c446bd0492ca',
    messagingSenderId: '192964375295',
    projectId: 'budgettracker-48d4c',
    storageBucket: 'budgettracker-48d4c.appspot.com',
    iosClientId: '192964375295-hvvqblh7k531s3u2c2tsvrogdu8ur3nl.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgettrack',
  );
}
